# Generated by Django 4.1.13 on 2024-12-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetone', '0002_company_product_delete_account_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Course',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='onetone.course'),
        ),
    ]
