# Generated by Django 4.1.13 on 2024-12-08 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onetone', '0004_blog_topic_user_remove_student_courses_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_experience', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
